### ISSUE TITLE
Error in slider.js when using plone.app.widgets

### ISSUE THREAD

**Issue by fulv** [4teamwork/ftw.slider#44]
I'm trying to mix ftw.slider 2.2.0 with plone.app.widgets 1.8.0 on Plone 4.3.6.  When I install ftw.slider, I get this error in the js console:

    Uncaught TypeError: $(...).slick is not a function        slider.js:8

This seems to indicate that slick is not registered with jQuery, but it's the only error.  I would expect to see some other error from slick.min.js, but there isn't one.  I also replaced the minified version with a non-minified one, but the result is the same.

I was just wondering if you have tried running ftw.slider with plone.app.widgets, and whether you have any idea what might be wrong.

These are my version pins, and again, I'm using Plone 4.3.6:

    plone.app.contenttypes                = 1.1b5
    plone.app.event                       = 1.1.5
    plone.app.widgets                     = 1.8.0
    plone.formwidget.recurrence           = 1.2.6
    plone.app.z3cform                     = 1.0.1
    ftw.slider                            = 2.2.0

Thanks!

**Comment by elioschmutz** [comment]
@fulv Hmm... the problem is the Slick.js (https://github.com/kenwheeler/slick) which is used in ftw.slider (https://github.com/4teamwork/ftw.slider/blob/master/ftw/slider/browser/resources/slick.min.js).

It breaks after plone.app.widgets is registering the widgets.js.

Workaround:

You could patch the slick.min.js:

```
--- Clipboard
+++ Selection
@@ -18,7 +18,7 @@
 (function(factory) {
     'use strict';
     if (typeof define === 'function' && define.amd) {
-        define(['jquery'], factory);
+        factory(jQuery);
     } else if (typeof exports !== 'undefined') {
         module.exports = factory(require('jquery'));
     } else {
```
=> diff of the non-minified slick.js (https://github.com/kenwheeler/slick/blob/1.5.5/slick/slick.js)

hope it works for you...

**Comment by fulv** [comment]
Thanks a lot for the workaround!  It does work.  Though, if the condition in 

        if (typeof define === 'function' && define.amd) {

is true, then I don't understand why the original line with `define(['jquery'], factory)` doesn't work.
But thanks!

**Comment by fulv** [comment]
IOW, I'm wondering whether there is a bug in Slick, that causes it to not play well with other plugins that use require.js (or other special cases), or it's plone.app.widgets that will break other plugins because of some problem in how it's implemented.
