### ISSUE TITLE
Will you eventually support this product in Plone 5?

### ISSUE THREAD

**Issue by Robynstar** [4teamwork/ftw.slider#47]
Was just wondering if you had intentions of continuing this product forward into Plone 5. We started using it as it is responsive and relatively lightweight, but it currently doesn't work on Plone 5. Obviously it is early days for Plone 5 yet but would be nice to know if this product will be updated for it or if we should start looking for something else.

**Comment by jone** [comment]
We are currently not yet using it with Plone 5.
Why doesn't it work?
We currently do not have the resources to bring all our packages to Plone 5 at once, but we are working as we need the packages.
We will happily accept pull requests though!

**Comment by Robynstar** [comment]
Sorry I was more asking whether this was still a living product, not demanding you upgrade it right away! For example Products.Carousel has pretty much said that it is mothballed.
Having upgraded from 2.2.0 to 2.3.0 it now works once you add two blank portal_properties:

'types_not_searched' in  site_properties to stop this error
```
Traceback (innermost last):
Module ZPublisher.Publish, line 138, in publish 
Module ZPublisher.mapply, line 77, in mapply 
Module ZPublisher.Publish, line 48, in call_object 
Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 707, in installProducts 
Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 624, in installProduct
__traceback_info__: ('ftw.slider',) 
Module Products.GenericSetup.tool, line 374, in runAllImportStepsFromProfile
__traceback_info__: profile-ftw.slider:default 
Module Products.GenericSetup.tool, line 1268, in _runImportStepsFromContext 
Module Products.GenericSetup.tool, line 1113, in _doRunImportStep
__traceback_info__: propertiestool 
Module Products.CMFPlone.exportimport.propertiestool, line 37, in importPloneProperties 
Module Products.GenericSetup.utils, line 509, in _importBody 
Module Products.CMFPlone.exportimport.propertiestool, line 106, in _importNode 
Module Products.CMFPlone.exportimport.propertiestool, line 149, in _initObjects 
Module Products.CMFPlone.exportimport.propertiestool, line 79, in _importNode 
Module Products.GenericSetup.utils, line 735, in _initProperties 
ValueError: undefined property 'types_not_searched' 
```
and  'metaTypesNotToList' in navtree_properties to stop this error
```
Traceback (innermost last):
Module ZPublisher.Publish, line 138, in publish 
Module ZPublisher.mapply, line 77, in mapply 
Module ZPublisher.Publish, line 48, in call_object 
Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 707, in installProducts 
Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 624, in installProduct
__traceback_info__: ('ftw.slider',) 
Module Products.GenericSetup.tool, line 374, in runAllImportStepsFromProfile
__traceback_info__: profile-ftw.slider:default 
Module Products.GenericSetup.tool, line 1268, in _runImportStepsFromContext 
Module Products.GenericSetup.tool, line 1113, in _doRunImportStep
__traceback_info__: propertiestool 
Module Products.CMFPlone.exportimport.propertiestool, line 37, in importPloneProperties 
Module Products.GenericSetup.utils, line 509, in _importBody 
Module Products.CMFPlone.exportimport.propertiestool, line 106, in _importNode 
Module Products.CMFPlone.exportimport.propertiestool, line 149, in _initObjects 
Module Products.CMFPlone.exportimport.propertiestool, line 79, in _importNode 
Module Products.GenericSetup.utils, line 735, in _initProperties 
ValueError: undefined property 'metaTypesNotToList' 
```

**Comment by WouterVH** [comment]
after these errors, you get a third
``
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 213, in __call__
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 686, in installProducts
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 603, in installProduct
   - __traceback_info__: ('plonetheme.onegov',)
  Module Products.GenericSetup.tool, line 379, in runAllImportStepsFromProfile
   - __traceback_info__: profile-plonetheme.onegov:default
  Module Products.GenericSetup.tool, line 1414, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1226, in _doRunImportStep
   - __traceback_info__: typeinfo
  Module Products.CMFCore.exportimport.typeinfo, line 225, in importTypesTool
  Module Products.GenericSetup.utils, line 853, in importObjects
   - __traceback_info__: portal_types
  Module Products.GenericSetup.utils, line 849, in importObjects
   - __traceback_info__: types/ftw.slider.Pane
  Module Products.GenericSetup.utils, line 512, in _importBody
  Module Products.CMFCore.exportimport.typeinfo, line 60, in _importNode
  Module Products.GenericSetup.utils, line 784, in _initProperties
  Module plone.dexterity.fti, line 294, in _updateProperty
  Module plone.dexterity.utils, line 52, in resolveDottedName
  Module zope.dottedname.resolve, line 38, in resolve
  Module None, line 3, in <module>
ImportError: cannot import name PloneMessageFactory
``

**Comment by WouterVH** [comment]
Above errors can be fixed manually,
but then you get this:
```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 213, in __call__
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 686, in installProducts
  Module Products.CMFQuickInstallerTool.QuickInstallerTool, line 603, in installProduct
   - __traceback_info__: ('plonetheme.onegov',)
  Module Products.GenericSetup.tool, line 379, in runAllImportStepsFromProfile
   - __traceback_info__: profile-plonetheme.onegov:default
  Module Products.GenericSetup.tool, line 1414, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1226, in _doRunImportStep
   - __traceback_info__: typeinfo
  Module Products.CMFCore.exportimport.typeinfo, line 225, in importTypesTool
  Module Products.GenericSetup.utils, line 853, in importObjects
   - __traceback_info__: portal_types
  Module Products.GenericSetup.utils, line 849, in importObjects
   - __traceback_info__: types/ftw.slider.Pane
  Module Products.GenericSetup.utils, line 512, in _importBody
  Module Products.CMFCore.exportimport.typeinfo, line 60, in _importNode
  Module Products.GenericSetup.utils, line 784, in _initProperties
  Module plone.dexterity.fti, line 294, in _updateProperty
  Module plone.dexterity.utils, line 52, in resolveDottedName
  Module zope.dottedname.resolve, line 38, in resolve
  Module None, line 3, in <module>
ImportError: cannot import name PloneMessageFactory
```
